# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Market Place' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Market Place
	pod 'AlamofireObjectMapper','5.2'
	pod 'Kingfisher'

  target 'Market PlaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Market PlaceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
